site_name: 아이작의 번제 아이템 설명 모드 한국어 가이드
site_author: kohashiwakaba
repo_url: https://github.com/kohashiwakaba/Isaac-EID-Korean-Guide
repo_name: kohashiwakaba/Isaac-EID-Korean-Guide
plugins:
  - search
  - mkdocs_pymdownx_material_extras
nav:
  - 개요: index.md
  - 사용법: 
    - '기본 사용법': howto/basic.md
    - '다른 아이템과의 시너지': howto/advanced.md
    - '리마인더': howto/reminder.md
    - '알트 카인 레시피': howto/crafting.md
    - 'REPENTOGON': howto/repentogon.md
    - 'Github에서 바로 업데이트': howto/update-from-github.md
  - 옵션: 
    - '주요 옵션': config/configmenu.md
    - '설정 파일 직접 수정': config/lua.md
  - 자주 묻는 질문: faq.md
  - 추천 모드: recommended.md
  - 변경 내역: changelog.md
  - 모드 링크: https://steamcommunity.com/sharedfiles/filedetails/?id=836319872
  - API(외부 링크): https://github.com/wofsauge/External-Item-Descriptions/wiki
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: ko
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc:
        permalink: True
    - toc.integrate
    - navigation.top
    - header.autohide
    - navigation.footer
  palette: 
    scheme: dracula
    primary: deep purple
    accent: deep purple
  font:
    text: IBM Plex Sans KR

extra_css: 
  - css/pymdownx.css
  - css/wakaba.css
markdown_extensions:
  - tables
  - md_in_html
  - admonition
  - def_list
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
copyright: Copyright &copy; 2022 kohashiwakaba aka. 미카